substitutions:
  _REGION: "europe-west1"
  _REPO:   "rag-demo-repo"
  _TAG:    "manual"

options:
  substitutionOption: ALLOW_LOOSE

steps:
# 1️⃣ Build
- name: gcr.io/cloud-builders/docker
  id: Build
  args:
    - build
    - -t
    - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/rag-demo:${_TAG}"
    - .

# 2️⃣ Push
- name: gcr.io/cloud-builders/docker
  id: Push
  args:
    - push
    - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/rag-demo:${_TAG}"

# 3️⃣ Deploy
- name: gcr.io/cloud-builders/gcloud
  id: Deploy
  args:
    - run
    - deploy
    - rag-demo
    - --image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/rag-demo:${_TAG}
    - --region=${_REGION}
    - --platform=managed
    - --memory=4Gi
    - --timeout=600s
    - --min-instances=0
    - --max-instances=3
    - --allow-unauthenticated

images:
- "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/rag-demo:${_TAG}"
