substitutions:
  _REGION: "europe-west1"
  _REPO: "demo-repo"

steps:
# 1. Build image
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/demo-api:$SHORT_SHA", "."]

# 2. Push image
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/demo-api:$SHORT_SHA"]

# 3. Deploy to Cloud Run
- name: "gcr.io/cloud-builders/gcloud"
  args:
    ["run", "deploy", "demo-api",
     "--image", "$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/demo-api:$SHORT_SHA",
     "--region", "$_REGION",
     "--platform", "managed",
     "--allow-unauthenticated",
     "--memory", "512Mi",
     "--min-instances", "0"]

images:
- "$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/demo-api:$SHORT_SHA"