steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t','$REGION-docker.pkg.dev/$PROJECT_ID/demo-repo/demo-api:$SHORT_SHA','.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push','$REGION-docker.pkg.dev/$PROJECT_ID/demo-repo/demo-api:$SHORT_SHA']

- name: 'gcr.io/cloud-builders/gcloud'
  args:
    ['run','deploy','demo-api',
     '--image','$REGION-docker.pkg.dev/$PROJECT_ID/demo-repo/demo-api:$SHORT_SHA',
     '--region','$REGION',
     '--platform','managed',
     '--allow-unauthenticated',
     '--memory','512Mi',
     '--min-instances','0']
images:
- '$REGION-docker.pkg.dev/$PROJECT_ID/demo-repo/demo-api:$SHORT_SHA'
